"""Add mode column

Revision ID: 098dcaa0fdd9
Revises: 3884d5c909fe
Create Date: 2025-05-04 19:37:19.262263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '098dcaa0fdd9'
down_revision = '3884d5c909fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
