"""Add UserTrack table

Revision ID: 3884d5c909fe
Revises: 3a9cc5e99c28
Create Date: 2025-05-04 19:32:02.283739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3884d5c909fe'
down_revision = '3a9cc5e99c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=False),
    sa.Column('song_duration', sa.Integer(), nullable=False),
    sa.Column('times_played', sa.Integer(), nullable=False),
    sa.Column('total_ms_listened', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acousticness', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('liveness', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('danceability', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('danceability')
        batch_op.drop_column('liveness')
        batch_op.drop_column('acousticness')

    op.drop_table('user_tracks')
    # ### end Alembic commands ###
