"""Add name, gender, dob, and mobile to User model

Revision ID: 3a9cc5e99c28
Revises: a3ae3a9404d8
Create Date: 2025-04-30 17:35:08.989138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9cc5e99c28'
down_revision = 'a3ae3a9404d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mobile')
        batch_op.drop_column('dob')
        batch_op.drop_column('gender')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
