"""updated track table

Revision ID: 42ffe72905de
Revises: 098dcaa0fdd9
Create Date: 2025-05-04 20:00:41.997161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ffe72905de'
down_revision = '098dcaa0fdd9'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('ix_tracks_user_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('playlist_id')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'playlists', ['playlist_id'], ['id'])
        batch_op.create_index('ix_tracks_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
