"""Add is_accepted to friend

Revision ID: 45ff431d0839
Revises: d7a2af79aed3
Create Date: 2025-05-10 10:36:52.676742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ff431d0839'
down_revision = 'd7a2af79aed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend', schema=None) as batch_op:
        batch_op.drop_column('is_accepted')

    # ### end Alembic commands ###
